### ISSUE TITLE
download data not working

### ISSUE THREAD

**Issue by verdugvi** [kjordahl/SciPy-Tutorial-2015#3]
The link neither the download_data.py are able to download the data.

**Comment by paulathomas** [comment]
Yep, the page access is forbidden (ie private). Any thoughts?

**Comment by kjordahl** [comment]
Sorry for the delay, the data file has now been uploaded as [tutorial_data.zip](https://github.com/kjordahl/SciPy-Tutorial-2015/releases/download/v1.0/tutorial_data.zip) and the instructions and download script updated accordingly.
